name: Nuxt Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: svIndicium/Workflows/.github/workflows/nuxt-build.yml@master
  build-docker:
    needs: build
    uses: svIndicium/Workflows/.github/workflows/nuxt-docker-build.yml@master
